### ISSUE TITLE
What about support for wal2json or pgoutput plugin?

### ISSUE THREAD

**Issue by dko-slapdash** [kibae/pg-logical-replication#10]
Using test_decoding plugin is kinda... hack... from both elegancy and performance perspectives.

- wal2json is supported by e.g. AWS RDS/Aurora, https://github.com/eulerto/wal2json
- pgoutput is a built-in standard for Postgres (it's used in e.g. CREATE SUBSCRIPTION command), and it's supported in https://github.com/kagis/pgwire client library

**Comment by fivetran-andydreyfuss** [comment]
@dko-slapdash do you have or know of benchmarks to support your assertion that test_decoding is less performant than other plugins?

**Comment by kibae** [comment]
Hi, @dko-slapdash 
You are right. The handling of "test_decoding" is tricky and messy. thanks for the good point. 👍 
This project is being rewritten using typescript. Better plugins like wal2json and decoderbufs are also available.

Take a look at the ts-main branch.
https://github.com/kibae/pg-logical-replication/tree/ts-main

I don't have a README ready yet, but I can show you how to use wal2json with test code.
https://github.com/kibae/pg-logical-replication/blob/ts-main/src/test/decoder-wal2json.spec.ts

**Comment by kibae** [comment]
The project has been updated to 2.x. You can use wal2json plugin. Please try it out and let me know if you have any questions. 🙏
