### ISSUE TITLE
Error safety

### ISSUE THREAD

**Issue by pauldraper** [kibae/pg-logical-replication#11]
The flush LSN should only be sent if the operation has completed successfully.

If there is an error while processing (say, when forwarding to another data store that is temporarily unavailable), the flush LSN should not be sent, lest the WAL be lost.

It doesn't seem there is a good way to do that.

**Comment by kibae** [comment]
Thanks for the good point.
This project is being rewritten with typescript(**ts-main** branch). I have modified the code to perform acknowledge after emitting a data event.
If the event listener throws an error, the acknowledge will not be processed.

https://github.com/kibae/pg-logical-replication/blob/ts-main/src/logical-replication-service.ts#L107

Let me know if you have any better suggestions. Thank you.

**Comment by pauldraper** [comment]
The problem with that is when the operation is asynchronous, which I suspect will be quite often.

I find Node.JS streams to be somewhat awkward.

Nor does it permit batch processing the events.

I recommend adding an `acknowledge()` method.

**Comment by kibae** [comment]
@pauldraper understood. 👍 
I will add an `acknowledge()` method and the option to disable automatically acknowledge after all data events.

**Comment by kibae** [comment]
https://github.com/kibae/pg-logical-replication/commit/e5d4c3571c4f664ec2a5db3bcd000a17c70abf54#diff-7550665dc51b7cf56840d32fbcfab81266c05d606d04d5088379353c20f41b3b

@pauldraper Exposed `acknowledge()` method and added options for manual acknowledgment. How about this? 🙏
