### ISSUE TITLE
Clarification Needed Regarding Transaction Logs and Rolled-Back Transactions

### ISSUE THREAD

**Issue by alighassabbashi2019** [kibae/pg-logical-replication#23]
Hi, I have two question: 
1- I need to be ensure that all the related logs of a transaction will be emitted all at once or not?
2- Does this package emit rolled back transactions?

Thanks.

**Comment by kibae** [comment]
I apologize for the late response.

1. It depends on the output plugin used. In the case of wal2json, all changed records will be transmitted at once. For pgoutput, the changed records will be streamed. Therefore, if there is a transaction involving a large number of record changes, it is advisable to use pgoutput.
1. Rolled-back transactions are not transmitted. Only transactions that are committed and saved in the WAL are transmitted.
