### ISSUE TITLE
integer Arrays 'integer[]' do not parse

### ISSUE THREAD

**Issue by seriouscoderone** [kibae/pg-logical-replication#3]
Error parsing integer arrays 'integer[]'

The following parses
```integer_field[integer]:null```

The following does not parse
```integer_array_field[integer[]]:null```

**Comment by kibae** [comment]
Hi, @seriouscoderone 
This project is being rewritten using typescript. Better plugins like wal2json and decoderbufs are also available. How about trying out wal2json with the new version?
Take a look at the **ts-main** branch.
https://github.com/kibae/pg-logical-replication/tree/ts-main

We don't have a README ready yet, but we can tell you how to use it in our test code.
https://github.com/kibae/pg-logical-replication/blob/ts-main/src/test/decoder-wal2json.spec.ts

**Comment by kibae** [comment]
The project has been updated to 2.x. Various plugins can be used, so using a plugin other than test_decoding will solve it. 🙏
