### ISSUE TITLE
Postgresql string array data type string[] failed when parsing

### ISSUE THREAD

**Issue by minhdao** [kibae/pg-logical-replication#6]
Hi kibae,

We encountered some issues with Postgresql array data type. Can you add support for this?

Thank you,
Minh

**Comment by kibae** [comment]
Hi, @minhdao 

#3 It's a similar issue.

This project is being rewritten using typescript. Better plugins like wal2json and decoderbufs are also available. How about trying out wal2json with the new version?
Take a look at the ts-main branch.
https://github.com/kibae/pg-logical-replication/tree/ts-main

I don't have a README ready yet, but I can show you how to use wal2json with test code.
https://github.com/kibae/pg-logical-replication/blob/ts-main/src/test/decoder-wal2json.spec.ts

**Comment by kibae** [comment]
The project has been updated to 2.x. Various plugins can be used, so using a plugin other than test_decoding will solve it. 🙏
