### ISSUE TITLE
Streaming Performance

### ISSUE THREAD

**Issue by wwindcloud** [kibae/pg-logical-replication#9]
First of all, thanks for this great library, I can do some logical replication streaming from postgresql to redis and other customized stuff without relying too much on pg_recvlogical which is very error pruned and difficult to manipulate.

However, one thing I quickly run into is when there are a lot of xlog from the server, and the client side is slow to process the data, memory can easily get blown out ending up with heap out of memory crash. Increasing node maximum heap alleviate the situation a bit, but sooner or later same thing happen.

I have done some research on this and realized that hooking up "data" event disable native stream backpressure management, and digging a little further, I realized it's not really the fault of this library but upstream node-postgres, they are making Net.Stream backwards by emitting "data" event first before piping downstream. Since event emission is embedded deeply inside node-postgres, I don't think there's a simple PR solution to fix that, not to mention they will accept such an invasive fix easily.

So going back to my problem, I take your library and do some simple hack by passing a custom Net.Stream to pg.Client, after it get connected to a pg server, I disable the stream "data" event handler and pipe things to a transform stream which will call the original handlers in node-postgres, once "copyData" is received, I pipe it to another stream and handle things from there. No "data" event emission and backpressure is handled automatically. Node memory goes from 1gb+ down to 100mb even when server keep sending data while the client is catching up slowly.

Another bonus from this implementation is that I can acknowledge flush_lsn anytime, that way I don't have to worry about crash as I can always stream from the last confirmed flush_lsn. Current "data" emission just force the lsn upon us without letting the user to make the acknowledgement.

After making up all these improvement, I have realized this is yet not another simple PR fix, therefore I would like to check with you if you have these kind of improvement in mind so i don't have to fork this library and maintain things myself and everybody can benefit. Thanks.

**Comment by jgutholm** [comment]
@wwindcloud Thanks for finding this issue. it doesn't seem like you are getting any response. Would you be willing to share what you've done? Are you still using it?

**Comment by kibae** [comment]
@wwindcloud Thank you for pointing out this issue and making an effort to resolve it. 👍
